namespace Prima.UOData.Types;

public enum GeneralInformationPacketSubcommand : byte
{
    InitializeFastWalkPrevention = 0x01,
    AddKeyToFastWalkStack = 0x02,
    CloseGenericGump = 0x04,
    ScreenSize = 0x05,
    PartySystem = 0x06,
    SetCursorHueSetMep = 0x08,
    SetCursorHue = 0x09,
    ClientLanguage = 0x0B,
    ClosedStatusGump = 0x0C,
    ThreeDClientAction = 0x0e,
    ClientType = 0x0F,
    RequestPopupMenu = 0x13,
    DisplayPopupMenu = 0x14,
    PopupEntrySelection = 0x15,
    CloseUserInterfaceWindows = 0x16,
    CodexOfWisdom = 0x17,
    EnableMapDiff = 0x18,
    ExtendedStats = 0x19,
    ExtendedStats2 = 0x1A,
    NewSpellbook = 0x1B,
    SpellSelectedClientSide = 0x1C,
    SendHouseRevisionState = 0x1D,
    CustomHousing = 0x20,
    AOS_AbilityIconConfirm = 0x21,
    Damage = 0x22,
    SEAbilityChange = 0x25,
    MountSpeed = 0x26,
    ServerChangeRaceRequest = 0x2A,
    ChangeRaceResponse = 0x2A,
    UseTargetedItem = 0x2C,
    CastTargetedSpell = 0x2D,
    UseTargetedSkill = 0x2E,
}
